### ISSUE TITLE
Error with dataloader

### ISSUE THREAD

**Issue by thematrixduo** [antoine77340/MIL-NCE_HowTo100M#11]
I got this error message while running dataloader with 40 workers to load Howto100M dataset. Just wondering if you ever encountered this. if not don't worry, it might be some problem with my setup.

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/workspace/pytorch_code/mmssl_graph/train_MILNCE.py", line 207, in main_worker
    train(train_loader, model, criterion, optimizer, scheduler, epoch, train_dataset, writer, args)
  File "/workspace/pytorch_code/mmssl_graph/train_MILNCE.py", line 225, in train
    for i_batch, sample_batch in enumerate(train_loader):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: __init__() missing 2 required positional arguments: 'stdout' and 'stderr'

## Environment
 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: Tesla V100
 - Any other relevant information: Running with Docker container

**Comment by antoine77340** [comment]
Hi,
This might be due to a decoding error in ffmpeg.
Most people encounter this problem because they either have the wrong video paths or corrupted videos.

**Comment by thematrixduo** [comment]
Thanks. I identified this video file which causes the error: HowTo100M/qMqUiprqXwU.mp4
Not sure if it is corrupted during downloading though. You might want to give it a check.
